model:
  name: "Qwen/Qwen2.5-Coder-7B-Instruct"
  trust_remote_code: true
  use_cache: false
  
data:
  max_length: 4096
  processed_data_path: "./processed_data"
  
training:
  # These will be auto-adjusted based on GPU
  batch_size: auto  
  gradient_accumulation_steps: auto
  
  # Fixed parameters
  learning_rate: 0.0005
  num_epochs: 3
  warmup_steps: 100
  weight_decay: 0.01
  
  # Optimization
  fp16: true
  fp16_opt_level: "O2"
  gradient_checkpointing: true
  optim: "adamw_8bit"
  max_grad_norm: 1.0
  
  # Saving
  save_strategy: "steps"
  save_steps: 100
  save_total_limit: 3
  eval_strategy: "steps"
  eval_steps: 100
  load_best_model_at_end: true
  metric_for_best_model: "eval_f1"
  greater_is_better: true
  
  # Logging
  logging_steps: 10
  logging_first_step: true
  report_to: "none"
  
  # Class weighting
  vulnerable_weight: 2.0
  
lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  bias: "none"
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"

paths:
  output_dir: "./output"
  cache_dir: "./cache"
  log_dir: "./logs"
  
mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "ftaudit-cloud"
  run_name: auto
  tags:
    environment: "cloud"
    model: "qwen"
    task: "vulnerability-detection"
    
metrics:
  vulnerable_token: "vulnerable"
  safe_token: "safe"
  log_confusion_matrix: true
  save_classification_report: true
  minimum_recall: 0.90
  minimum_precision: 0.70
  
# GPU-specific overrides
gpu_configs:
  a100-80gb:
    batch_size: 16
    gradient_accumulation_steps: 1
    
  a100-40gb:
    batch_size: 8
    gradient_accumulation_steps: 2
    
  rtx-24gb:
    batch_size: 4
    gradient_accumulation_steps: 4
    
  rtx-16gb:
    batch_size: 2
    gradient_accumulation_steps: 8

  rtx-a6000-48gb:
    batch_size: 6
    gradient_accumulation_steps: 3
    
  default:
    batch_size: 1
    gradient_accumulation_steps: 16