model:
  name: "Qwen/Qwen2.5-Coder-7B-Instruct"
  trust_remote_code: true
  use_cache: false
  
data:
  max_length: 4096
  processed_data_path: "./processed_data"
  
training:
  batch_size: auto  
  gradient_accumulation_steps: auto
  
  learning_rate: 0.0002
  num_epochs: 3
  warmup_steps: 100
  weight_decay: 0.01
  
  # Memory optimization
  fp16: true
  fp16_opt_level: "O2"
  gradient_checkpointing: true
  optim: "adamw_8bit"
  max_grad_norm: 1.0
  
  # Checkpointing
  save_strategy: "steps"
  save_steps: 500
  save_total_limit: 3
  eval_strategy: "no"
  eval_steps: 500
  load_best_model_at_end: true
  metric_for_best_model: "eval_f1_macro"
  greater_is_better: true
  
  logging_steps: 10
  logging_first_step: true
  report_to: "none"
  
  # FTSA uses balanced weights for vulnerable classes
  vulnerable_weight: 2.5
  
lora:
  # FTSA LoRA configuration
  r: 32
  lora_alpha: 64
  lora_dropout: 0.1
  bias: "none"
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"

paths:
  output_dir: "./output"
  cache_dir: "./cache"
  log_dir: "./logs"
  
mlflow:
  tracking_uri: "https://mlflow.9a.au"
  experiment_name: "smartaudit-student"
  run_name: auto
  tags:
    environment: "cloud"
    model: "qwen2.5-7b"
    task: "multiclass-vulnerability-detection"
    framework: "smartaudit"
    
metrics:
  log_confusion_matrix: true
  save_classification_report: true
  minimum_recall_vulnerable: 0.95
  minimum_f1_macro: 0.85