model:
  name: "Qwen/Qwen2.5-Coder-7B-Instruct"
  trust_remote_code: true
  use_cache: false
  
data:
  max_length: 4096
  processed_data_path: "./processed_data"
  
training:
  # Auto-detect optimal batch size or set manually
  batch_size: auto  
  gradient_accumulation_steps: auto
  
  learning_rate: 0.0005
  num_epochs: 3
  warmup_steps: 100
  weight_decay: 0.01
  
  # Memory optimization
  fp16: true
  fp16_opt_level: "O2"
  gradient_checkpointing: true
  optim: "adamw_8bit"
  max_grad_norm: 1.0
  
  # Checkpointing
  save_strategy: "steps"
  save_steps: 500
  save_total_limit: 3
  eval_strategy: "no"
  eval_steps: 500
  load_best_model_at_end: false
  metric_for_best_model: "eval_f1"
  greater_is_better: true
  
  logging_steps: 10
  logging_first_step: true
  report_to: "none"
  
  # Weight for vulnerable class
  vulnerable_weight: 2.0
  
lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  bias: "none"
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"

paths:
  output_dir: "./output"
  cache_dir: "./cache"
  log_dir: "./logs"
  
mlflow:
  tracking_uri: "https://mlflow.9a.au"
  experiment_name: "smart-audit-cloud"
  run_name: auto
  tags:
    environment: "cloud"
    model: "qwen"
    task: "vulnerability-detection"
    
metrics:
  task_type: "multiclass"  # Options: "binary", "multiclass"
  vulnerable_token: "vulnerable"
  safe_token: "safe"
  log_confusion_matrix: true
  save_classification_report: true
  minimum_recall: 0.90
  minimum_precision: 0.70